name       : atril
version    : 1.20.1
release    : 12
source     :
    - https://pub.mate-desktop.org/releases/1.20/atril-1.20.1.tar.xz : 25f44a7cfde76d9e2e5909351f0fe445b4e00d8e6e3862befff462f52487d5c8
license    : GPL-2.0-only
component  : desktop.mate
summary    : MATE Desktop Document Viewer
description: |
    Atril is a document viewer capable of displaying multiple and single page document formats like PDF and Postscript
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(libcaja-extension)
    - pkgconfig(libgxps)
    - pkgconfig(libsecret-1)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(poppler)
    - pkgconfig(sm)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
setup      : |
    %configure --disable-static \
               --enable-epub
build      : |
    %make
install    : |
    %make_install
