name       : atril
version    : 1.22.1
release    : 19
source     :
    - https://github.com/mate-desktop/atril/archive/v1.22.1.tar.gz : 514e86fc25832ee1b5bd5d9f83d8a88e1feddd44c5a88f76fa0f1617357ed561
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE Desktop Document Viewer
description: |
    Atril is a document viewer capable of displaying multiple and single page document formats like PDF and Postscript
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(gtk-doc)
    - pkgconfig(libcaja-extension)
    - pkgconfig(libgxps)
    - pkgconfig(libsecret-1)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(poppler)
    - pkgconfig(sm)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
    - mate-common
    - yelp-tools
setup      : |
    %autogen --disable-static \
             --enable-epub \
             --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
