name       : atril
version    : 1.24.0
release    : 28
source     :
    - https://github.com/mate-desktop/atril/archive/v1.24.0.tar.gz : d4062b05a776f4384d64a69e3399d3dfb3981f5c086fe8d44ecf9ded34527d6d
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE Desktop Document Viewer
description: |
    Atril is a document viewer capable of displaying multiple and single page document formats like PDF and Postscript
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(gtk-doc)
    - pkgconfig(libcaja-extension)
    - pkgconfig(libgxps)
    - pkgconfig(libsecret-1)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(poppler)
    - pkgconfig(sm)
    - pkgconfig(synctex)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
    - mate-common
    - yelp-tools
setup      : |
    %autogen --disable-static \
             --enable-epub \
             --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
