name       : atril
version    : 1.20.0
release    : 10
source     :
    - https://pub.mate-desktop.org/releases/1.20/atril-1.20.0.tar.xz : 36d0515675951923f1d39c37ef6d1eacb4221bb33dc947d6e6c532d858976998
license    : GPL-2.0
component  : desktop.mate
summary    : MATE Desktop Document Viewer
description: |
    Atril is a document viewer capable of displaying multiple and single page document formats like PDF and Postscript
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(libcaja-extension)
    - pkgconfig(libgxps)
    - pkgconfig(libsecret-1)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(poppler)
    - pkgconfig(sm)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
setup      : |
    %configure --disable-static \
               --enable-epub
build      : |
    %make
install    : |
    %make_install
