name       : atril
version    : 1.18.1
release    : 6
source     :
    - https://pub.mate-desktop.org/releases/1.18/atril-1.18.1.tar.xz : 8504c0164faf9a0763118d444007dd2bc655dd0dcd0c6ecfff163080b61883f2
license    : GPL-2.0
component  : desktop.mate
summary    : MATE Desktop Document Viewer
description: |
    Atril is a document viewer capable of displaying multiple and single page document formats like PDF and Postscript
builddeps  :
    - pkgconfig(cairo-pdf)
    - pkgconfig(cairo-ps)
    - pkgconfig(ddjvuapi)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(sm)
    - pkgconfig(gtk+-x11-3.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(libgxps)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libtiff-4)
    - pkgconfig(libxml-2.0)
    - pkgconfig(poppler-glib)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(zlib)
    - itstool
setup      : |
    %configure --disable-static \
               --enable-epub
build      : |
    %make
install    : |
    %make_install
