name       : atril
version    : 1.24.1
release    : 31
source     :
    - https://github.com/mate-desktop/atril/releases/download/v1.24.1/atril-1.24.1.tar.xz : b48372a89813f31d2635de02d9e92ba38e794daddf625f06d80c3793248bde1a
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE Desktop Document Viewer
description: |
    Atril is a document viewer capable of displaying multiple and single page document formats like PDF and Postscript
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(gtk-doc)
    - pkgconfig(libcaja-extension)
    - pkgconfig(libgxps)
    - pkgconfig(libsecret-1)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(poppler)
    - pkgconfig(sm)
    - pkgconfig(synctex)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
    - mate-common
    - yelp-tools
setup      : |
    %autogen --disable-static \
             --enable-epub \
             --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
