name       : atril
version    : 1.26.0
release    : 36
source     :
    - https://github.com/mate-desktop/atril/releases/download/v1.26.0/atril-1.26.0.tar.xz : 715e766eaede3fa5d8ca300fa3319fb2b63055dfdc6e971d8750c2aec624e45f
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE Desktop Document Viewer
description: |
    Atril is a document viewer capable of displaying multiple and single page document formats like PDF and Postscript
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(gtk-doc)
    - pkgconfig(libcaja-extension)
    - pkgconfig(libgxps)
    - pkgconfig(libsecret-1)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(libgxps)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(poppler)
    - pkgconfig(sm)
    - pkgconfig(synctex)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
setup      : |
    %configure --disable-static \
        --enable-epub \
        --enable-gtk-doc
build      : |
    %make
install    : |
    %make_install
