name       : atril
version    : 1.14.2
release    : 1
source     :
    - http://pub.mate-desktop.org/releases/1.14/atril-1.14.2.tar.xz : 9a8eadd85bda4539560f01a2127be4d6c358c07c6a744c09d1fdb5bff7ce14f4
license    : GPL-2.0
component  : desktop.mate
summary    : MATE Desktop Document Viewer
description: |
    Atril is a document viewer capable of displaying multiple and single page document formats like PDF and Postscript
builddeps  :
    - pkgconfig(cairo-pdf)
    - pkgconfig(cairo-ps)
    - pkgconfig(ddjvuapi)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(sm)
    - pkgconfig(gtk+-x11-3.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(libsecret-1)
    - pkgconfig(libtiff-4)
    - pkgconfig(poppler-glib)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(webkit2gtk-4.0)
    - pkgconfig(zlib)
    - itstool
setup      : |
    %configure --disable-static --with-gtk=3.0
build      : |
    %make
install    : |
    %make_install
