name       : atril
version    : 1.20.3
release    : 16
source     :
    - https://pub.mate-desktop.org/releases/1.20/atril-1.20.3.tar.xz : 79dbcdf663a7a40194ece1b1ac3304a35b6828b0a68eed286c0e9c319dc77903
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : MATE Desktop Document Viewer
description: |
    Atril is a document viewer capable of displaying multiple and single page document formats like PDF and Postscript
builddeps  :
    - pkgconfig(ddjvuapi)
    - pkgconfig(libcaja-extension)
    - pkgconfig(libgxps)
    - pkgconfig(libsecret-1)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(poppler)
    - pkgconfig(sm)
    - pkgconfig(webkit2gtk-4.0)
    - itstool
setup      : |
    %configure --disable-static \
               --enable-epub
build      : |
    %make
install    : |
    %make_install
